services:
  rist-bonding-dev:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - rist-bonding-dev:latest
    container_name: rist-bonding-dev-ci
    privileged: true  # Required for network namespace management
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN  # Required for mounting /run/netns and namespace operations
    volumes:
      - .:/workspace
      - /lib/modules:/lib/modules:ro
      - /run/netns:/run/netns:shared  # Share network namespaces with host
      # Use named volume for cargo cache in CI
      - cargo-cache:/root/.cargo
    working_dir: /workspace
    command: sleep infinity
    environment:
      - CARGO_HOME=/root/.cargo
    # Enable interactive mode for CI
    stdin_open: true
    tty: true

volumes:
  cargo-cache: