services:
  rist-bonding-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rist-bonding-dev
    cap_add:
      - NET_ADMIN
    volumes:
      - .:/workspace
      - /lib/modules:/lib/modules:ro
      - ${SSH_AUTH_SOCK}:/ssh-agent
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    working_dir: /workspace
    command: sleep infinity
