services:
  rist-bonding-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rist-bonding-dev
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN  # Required for mounting /run/netns and namespace operations
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: sleep infinity
