services:
  rist-bonding-dev:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - rist-bonding-dev:latest
    container_name: rist-bonding-dev-ci
    privileged: true  # Required for network namespace management
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN  # Required for mounting /run/netns and namespace operations
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: sleep infinity
    environment:
      - CARGO_HOME=/root/.cargo
    stdin_open: true
    tty: true
https://lichess.org/analysis#5