services:
  rist-bonding-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rist-bonding-dev
    cap_add:
      - NET_ADMIN
    volumes:
      - .:/workspace
      - /lib/modules:/lib/modules:ro
    working_dir: /workspace
    command: sleep infinity
