[package]
name = "netlink-sim"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
tokio = { version = "1", features = ["full"] }
rand = { version = "0.8", features = ["std", "std_rng"] }
