name: Docker Development Environment

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'Dockerfile'
      - 'docker-compose.yml'
      - '.devcontainer/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'Dockerfile' 
      - 'docker-compose.yml'
      - '.devcontainer/**'

jobs:
  validate-devcontainer:
    name: Validate Development Container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build development container
        run: docker-compose build rist-bonding-dev
      
      - name: Test development environment setup
        run: |
          docker-compose run --rm rist-bonding-dev bash -c "
            echo 'Testing Rust toolchain...'
            cargo --version
            rustc --version
            
            echo 'Testing GStreamer availability...'
            gst-inspect-1.0 --version
            
            echo 'Testing basic project build...'
            cargo check --workspace
          "
      
      - name: Test network capabilities (local RIST operations)
        run: |
          docker-compose run --rm rist-bonding-dev bash -c "
            echo 'Setting up local network namespaces for RIST testing...'
            
            # Create network namespaces for isolated RIST endpoints
            ip netns add rist-sender 2>/dev/null || true
            ip netns add rist-receiver 2>/dev/null || true
            
            # Create veth pairs for local RIST communication
            ip link add veth-sender type veth peer name veth-sender-peer 2>/dev/null || true
            
            # Move interfaces to respective namespaces
            ip link set veth-sender-peer netns rist-sender 2>/dev/null || true
            
            # Configure interfaces
            ip addr add 192.168.100.1/24 dev veth-sender 2>/dev/null || true
            ip link set veth-sender up 2>/dev/null || true
            ip netns exec rist-sender ip addr add 192.168.100.2/24 dev veth-sender-peer 2>/dev/null || true
            ip netns exec rist-sender ip link set veth-sender-peer up 2>/dev/null || true
            ip netns exec rist-sender ip link set lo up 2>/dev/null || true
            
            echo 'Testing local connectivity...'
            ping -c 2 -W 1 127.0.0.1
            
            echo 'Listing network interfaces...'
            ip addr show | grep -E 'veth|lo'
            
            echo 'Listing network namespaces...'
            ip netns list
          "
  
  validate-dockerfile:
    name: Validate Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          failure-threshold: warning
          ignore: DL3008,DL3009  # Allow apt packages without pinned versions for dev env